#ifndef secure_sign_rust_h
#define secure_sign_rust_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

namespace secure_sign_rust {

extern "C" {

uint64_t add(uint64_t left, uint64_t right);

}  // extern "C"

}  // namespace secure_sign_rust

#endif  // secure_sign_rust_h
