#ifndef secure_sign_rust_h
#define secure_sign_rust_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

uint64_t der_to_p1363(uint64_t left, uint64_t right);

#endif  /* secure_sign_rust_h */
