extern crate cbindgen;

use std::env;

fn generate_c_headers() {
    let crate_dir: String = env::var("CARGO_MANIFEST_DIR").unwrap();
    let header_path: &str = "generated/include/libsecure_sign_rust.h";

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_language(cbindgen::Language::Cxx)
        .with_include_guard("secure_sign_rust_h")
        .with_autogen_warning("/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */")
        .with_namespace("secure_sign_rust")
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(header_path);
}

fn main() {
    println!("cargo:rerun-if-changed=src/lib.rs");

    if std::env::var("CARGO_CFG_CLIPPY").is_err() {
        extern crate cbindgen; 
        generate_c_headers();
    }
}